---
- name: Gather distribution info
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version_compare('7', '==')
      msg: "This role can only be run against RHEL/CENTOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  assert:
      that: ansible_version.full is version_compare(rhel7stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ rhel7stig_min_ansible_version }} or greater
  tags:
      - always
      
- name: Do not count this as a failure
  ansible.builtin.command: /bin/false
  ignore_errors: yes

- name: FIPS turned on
  set_fact:
      fips_value: '1'
  when:
      - rhel7stig_use_fips
  tags:
      - RHEL-07-021350

- import_tasks: prelim.yml
  become: yes
  tags:
      - prelim_tasks
      - run_audit

- import_tasks: pre_remediation_audit.yml
  when:
      - run_audit
  tags:
      - run_audit

- name: Gather the package facts
  package_facts:
      manager: auto
  tags:
      - always

- name: flush handlers
  meta: flush_handlers

- name: Reboot system
  reboot:
  when:
  - not rhel7stig_skip_reboot

- import_tasks: post_remediation_audit.yml
  when:
      - run_audit

- name: Show Audit Summary
  debug:
      msg: "{{ audit_results.split('\n') }}"
  when:
      - run_audit
